name: payfast
description: A wrapper library built to make using the Payfast API with Flutter much easier.
version: 0.0.0
homepage: https://github.com/JoshMunstermann/payfast

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies: {crypto: ^3.0.2}

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

